apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: challenge1
  name: challenge1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: challenge1
  type: NodePort
status:
  loadBalancer: {}
